version: "3.9"
services:
  ### ==================
  ### KONGA
  ### ==================

  konga:
    image: pantsel/konga:latest
    container_name: konga_service
    environment:
      - "DB_ADAPTER=postgres"
      - "DB_HOST=kong-database"
      - "DB_PORT=5432"
      - "DB_USER=user"
      - "DB_PASSWORD=12345"
      - "DB_DATABASE=kong_db"
      - "KONGA_API_URL=http://localhost:8001"
    ports:
      - "1337:1337"
    depends_on:
      - kong
      - kong-database
    networks:
      - blog_network

  ### ==================
  ### KONG DB
  ### ==================

  kong-database:
    image: postgres:9.6
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=kong_db
    ports:
      - 5434:5432
    networks:
      - blog_network

  ### ==================
  ### KONG
  ### ==================
  kong:
    # image: kong:latest
    # restart: always
    build:
      dockerfile: Dockerfile
      context: .
    container_name: kong_service
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
      - KONG_PG_DATABASE=kong_db
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_PLUGINS=jwt,kong-jwt2header,cors
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    networks:
      - blog_network

  konga-prepare:
    container_name: konga_prepare_service
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong-database:user@12345:5432/kong_db"
    networks:
      - blog_network
    # restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  ### ===================
  ### KONG MIGRATE SERVICE
  ### ===================
  kong-migrate:
    container_name: kong_migrate_service
    image: kong:latest
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
    depends_on:
      - kong-database
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
volumes:
  pgdata:
